packages:
  - 'apps/*'
  - 'packages/*'
injectWorkspacePackages: true
allowBuilds:
  '@prisma/engines': false
  better-sqlite3: false
  electron-winstaller: false
  prisma: false
  sharp: false
  tesseract.js: false
  unrs-resolver: false
